/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Float = IDL.Float64;
export const PanelProduct = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'productId' : IDL.Nat,
  'isActive' : IDL.Bool,
  'badge' : IDL.Text,
  'price' : Float,
});
export const Time = IDL.Int;
export const Testimonial = IDL.Record({
  'content' : IDL.Text,
  'createdAt' : Time,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'author' : IDL.Text,
  'customerId' : IDL.Nat,
  'rating' : IDL.Nat,
});
export const SiteSettings = IDL.Record({
  'contactTelegram' : IDL.Text,
  'heroSubtitle' : IDL.Text,
  'contactEmail' : IDL.Text,
  'heroTitle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPanelProduct' : IDL.Func([PanelProduct], [IDL.Nat], []),
  'createTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
  'deletePanelProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
  'getActivePanelProducts' : IDL.Func([], [IDL.Vec(PanelProduct)], ['query']),
  'getActiveTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getAllPanelProducts' : IDL.Func([], [IDL.Vec(PanelProduct)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPanelProduct' : IDL.Func([IDL.Nat], [PanelProduct], ['query']),
  'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'seedData' : IDL.Func([], [], []),
  'updatePanelProduct' : IDL.Func([IDL.Nat, PanelProduct], [], []),
  'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
  'updateTestimonial' : IDL.Func([IDL.Nat, Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Float = IDL.Float64;
  const PanelProduct = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'productId' : IDL.Nat,
    'isActive' : IDL.Bool,
    'badge' : IDL.Text,
    'price' : Float,
  });
  const Time = IDL.Int;
  const Testimonial = IDL.Record({
    'content' : IDL.Text,
    'createdAt' : Time,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'author' : IDL.Text,
    'customerId' : IDL.Nat,
    'rating' : IDL.Nat,
  });
  const SiteSettings = IDL.Record({
    'contactTelegram' : IDL.Text,
    'heroSubtitle' : IDL.Text,
    'contactEmail' : IDL.Text,
    'heroTitle' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPanelProduct' : IDL.Func([PanelProduct], [IDL.Nat], []),
    'createTestimonial' : IDL.Func([Testimonial], [IDL.Nat], []),
    'deletePanelProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Nat], [], []),
    'getActivePanelProducts' : IDL.Func([], [IDL.Vec(PanelProduct)], ['query']),
    'getActiveTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getAllPanelProducts' : IDL.Func([], [IDL.Vec(PanelProduct)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPanelProduct' : IDL.Func([IDL.Nat], [PanelProduct], ['query']),
    'getSiteSettings' : IDL.Func([], [SiteSettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'seedData' : IDL.Func([], [], []),
    'updatePanelProduct' : IDL.Func([IDL.Nat, PanelProduct], [], []),
    'updateSiteSettings' : IDL.Func([SiteSettings], [], []),
    'updateTestimonial' : IDL.Func([IDL.Nat, Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };