/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Float = number;
export interface PanelProduct {
  'features' : Array<string>,
  'sortOrder' : bigint,
  'name' : string,
  'description' : string,
  'productId' : bigint,
  'isActive' : boolean,
  'badge' : string,
  'price' : Float,
}
export interface SiteSettings {
  'contactTelegram' : string,
  'heroSubtitle' : string,
  'contactEmail' : string,
  'heroTitle' : string,
}
export interface Testimonial {
  'content' : string,
  'createdAt' : Time,
  'role' : string,
  'isActive' : boolean,
  'author' : string,
  'customerId' : bigint,
  'rating' : bigint,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPanelProduct' : ActorMethod<[PanelProduct], bigint>,
  'createTestimonial' : ActorMethod<[Testimonial], bigint>,
  'deletePanelProduct' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getActivePanelProducts' : ActorMethod<[], Array<PanelProduct>>,
  'getActiveTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAllPanelProducts' : ActorMethod<[], Array<PanelProduct>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPanelProduct' : ActorMethod<[bigint], PanelProduct>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'seedData' : ActorMethod<[], undefined>,
  'updatePanelProduct' : ActorMethod<[bigint, PanelProduct], undefined>,
  'updateSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'updateTestimonial' : ActorMethod<[bigint, Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];